:Author: rohit_reddy
:Email: {rohitpreddi@gmail.com}
:Date: 12/05/2021
:Revision: version#
:License: Public Domain

= Project: Health of the transformer

Describe your project

== Step 1: Installation
To run the project in your system
1. Download the Transformer_Health.zip file. 
2. Extract it
3. Open the code in Aurduino IDE
4. Open the MATLAB code in MATLAB
5. Run the code.


== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── Transformer_Health.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact rohit_reddy https://id.arduino.cc/rohit_reddy

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Quantity
| R1 | 10k Resistor   | 10
| L1 | Red LED        | 5
| A1 | Arduino Zero   | 1
| A2 | Arduino UNO    | 1
| E1 | ESP8266        | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
